require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SomethingsController do

  # This should return the minimal set of attributes required to create a valid
  # Something. As you add validations to Something, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SomethingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all somethings as @somethings" do
      something = Something.create! valid_attributes
      get :index, {}, valid_session
      assigns(:somethings).should eq([something])
    end
  end

  describe "GET show" do
    it "assigns the requested something as @something" do
      something = Something.create! valid_attributes
      get :show, {:id => something.to_param}, valid_session
      assigns(:something).should eq(something)
    end
  end

  describe "GET new" do
    it "assigns a new something as @something" do
      get :new, {}, valid_session
      assigns(:something).should be_a_new(Something)
    end
  end

  describe "GET edit" do
    it "assigns the requested something as @something" do
      something = Something.create! valid_attributes
      get :edit, {:id => something.to_param}, valid_session
      assigns(:something).should eq(something)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Something" do
        expect {
          post :create, {:something => valid_attributes}, valid_session
        }.to change(Something, :count).by(1)
      end

      it "assigns a newly created something as @something" do
        post :create, {:something => valid_attributes}, valid_session
        assigns(:something).should be_a(Something)
        assigns(:something).should be_persisted
      end

      it "redirects to the created something" do
        post :create, {:something => valid_attributes}, valid_session
        response.should redirect_to(Something.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved something as @something" do
        # Trigger the behavior that occurs when invalid params are submitted
        Something.any_instance.stub(:save).and_return(false)
        post :create, {:something => {}}, valid_session
        assigns(:something).should be_a_new(Something)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Something.any_instance.stub(:save).and_return(false)
        post :create, {:something => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested something" do
        something = Something.create! valid_attributes
        # Assuming there are no other somethings in the database, this
        # specifies that the Something created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Something.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => something.to_param, :something => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested something as @something" do
        something = Something.create! valid_attributes
        put :update, {:id => something.to_param, :something => valid_attributes}, valid_session
        assigns(:something).should eq(something)
      end

      it "redirects to the something" do
        something = Something.create! valid_attributes
        put :update, {:id => something.to_param, :something => valid_attributes}, valid_session
        response.should redirect_to(something)
      end
    end

    describe "with invalid params" do
      it "assigns the something as @something" do
        something = Something.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Something.any_instance.stub(:save).and_return(false)
        put :update, {:id => something.to_param, :something => {}}, valid_session
        assigns(:something).should eq(something)
      end

      it "re-renders the 'edit' template" do
        something = Something.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Something.any_instance.stub(:save).and_return(false)
        put :update, {:id => something.to_param, :something => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested something" do
      something = Something.create! valid_attributes
      expect {
        delete :destroy, {:id => something.to_param}, valid_session
      }.to change(Something, :count).by(-1)
    end

    it "redirects to the somethings list" do
      something = Something.create! valid_attributes
      delete :destroy, {:id => something.to_param}, valid_session
      response.should redirect_to(somethings_url)
    end
  end

end
